---
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars:
   user_name: bess2025
   group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: Check the time
      command: datehhhjbhjkj
#      when: ansible_distribution == "serge" or ansible_processor_nproc == 2
    - name: create user bess
      user:
         name: "{{user_name}}"
         comment: Bess Admin
    - name: create group
      group:
         name: "{{group_name}}"
         state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present 

